server:
  port: 8084
  compression:
    enabled: true
    mime-types: application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
  servlet:
    context-path: /

logging:
  config: classpath:log4j2.xml

fastEventEngine:
  WaitStrategy: SleepingWaitStrategy
chronicleQueueBasePath: D:\\redtorch\\ChronicleQueue

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: mts
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/opt/dev/qts/qts.db

mybatis:
  mapper-locations: classpath:mapping/*.xml



